/**
 * Serialize an ERDiagram back to DBML (conceptual → physical approximation).
 *
 * Strategy:
 * - Each EREntity → Table with its attributes as columns.
 * - Each ERRelationship with 2 participants → Ref line (cardinality-aware).
 * - N:M relationships get their own junction table when they carry attributes.
 * - Relationship attributes on a 2-participant rel without own table are
 *   emitted as a comment next to the Ref.
 */

import type { ERAttribute, ERDiagram, EREntity, ERRelationship } from "~/types/er-model";

// ── Helpers ────────────────────────────────────────────────────────────────────

function indent(s: string): string {
  return `  ${s}`;
}

function attributeToColumn(attr: ERAttribute): string {
  const type = inferType(attr);
  const notes: string[] = [];

  if (attr.kind === "key") notes.push("pk");
  if (attr.kind === "derived") notes.push("note: 'derived'");
  if (attr.kind === "multivalued") notes.push("note: 'multivalued'");

  const notePart = notes.length ? ` [${notes.join(", ")}]` : "";
  return `${attr.name} ${type}${notePart}`;
}

/** Best-effort type inference from attribute name/kind. */
function inferType(attr: ERAttribute): string {
  if (attr.kind === "key") return "int";
  const n = attr.name.toLowerCase();
  if (n.endsWith("_id") || n === "id") return "int";
  if (n.includes("date") || n.includes("_at")) return "date";
  if (n.includes("price") || n.includes("amount") || n.includes("cost")) return "decimal";
  if (n.includes("count") || n.includes("age") || n.includes("year") || n.includes("num")) return "int";
  if (n.includes("flag") || n.includes("active") || n.includes("enabled")) return "boolean";
  return "varchar";
}

function entityToTable(entity: EREntity): string {
  const lines: string[] = [];
  lines.push(`Table ${entity.name} {`);

  // Flatten composite children inline
  const flatAttrs = flattenAttributes(entity.attributes);
  for (const attr of flatAttrs) {
    lines.push(indent(attributeToColumn(attr)));
  }

  if (entity.weak) {
    lines.push(indent(`Note: 'Weak entity'`));
  }

  lines.push("}");
  return lines.join("\n");
}

function flattenAttributes(attrs: ERAttribute[]): ERAttribute[] {
  const result: ERAttribute[] = [];
  for (const a of attrs) {
    if (a.kind === "composite" && a.children?.length) {
      result.push(...flattenAttributes(a.children));
    } else {
      result.push(a);
    }
  }
  return result;
}

/** Find the key attribute id for an entity (for FK column names). */
function keyAttrName(entity: EREntity): string {
  const key = entity.attributes.find((a) => a.kind === "key");
  return key?.name ?? `${entity.name.toLowerCase()}_id`;
}

/**
 * Determine DBML Ref operator from participant cardinalities.
 *   1  → 1  : -
 *   1  → N  : <
 *   N  → 1  : >
 *   N/M → N/M : <>
 */
function refOperator(fromCard: string, toCard: string): string {
  const many = (c: string) => c === "N" || c === "M";
  if (!many(fromCard) && !many(toCard)) return "-";
  if (!many(fromCard) && many(toCard)) return "<";
  if (many(fromCard) && !many(toCard)) return ">";
  return "<>";
}

// ── Main serializer ────────────────────────────────────────────────────────────

export function erToDmbl(diagram: ERDiagram): string {
  const entityMap = new Map(diagram.entities.map((e) => [e.id, e]));
  const blocks: string[] = [];

  // Header comment
  blocks.push(`// ${diagram.name}`);
  blocks.push(`// Generated by ER-Maker\n`);

  // Entity tables
  for (const entity of diagram.entities) {
    blocks.push(entityToTable(entity));
  }

  // Relationships
  const refs: string[] = [];
  const junctionTables: string[] = [];

  for (const rel of diagram.relationships) {
    if (rel.participants.length !== 2) continue;

    const [p1, p2] = rel.participants;
    const e1 = entityMap.get(p1.entityId);
    const e2 = entityMap.get(p2.entityId);
    if (!e1 || !e2) continue;

    const hasAttributes = rel.attributes.length > 0;
    const isNM =
      (p1.cardinality === "N" || p1.cardinality === "M") &&
      (p2.cardinality === "N" || p2.cardinality === "M");

    if (isNM && hasAttributes) {
      // Emit a junction table
      junctionTables.push(nmJunctionTable(rel, e1, e2));
      refs.push(`Ref: ${e1.name.toLowerCase()}_${e2.name.toLowerCase()}.${keyAttrName(e1)} > ${e1.name}.${keyAttrName(e1)}`);
      refs.push(`Ref: ${e1.name.toLowerCase()}_${e2.name.toLowerCase()}.${keyAttrName(e2)} > ${e2.name}.${keyAttrName(e2)}`);
    } else {
      const op = refOperator(p1.cardinality, p2.cardinality);
      const attrNote = hasAttributes
        ? ` [note: '${rel.name} attrs: ${rel.attributes.map((a) => a.name).join(", ")}']`
        : "";
      refs.push(`Ref: ${e1.name}.${keyAttrName(e1)} ${op} ${e2.name}.${keyAttrName(e2)}${attrNote}`);
    }
  }

  if (junctionTables.length) {
    blocks.push(...junctionTables);
  }

  if (refs.length) {
    blocks.push(refs.join("\n"));
  }

  return blocks.join("\n\n");
}

function nmJunctionTable(
  rel: ERRelationship,
  e1: EREntity,
  e2: EREntity,
): string {
  const tableName = `${e1.name.toLowerCase()}_${e2.name.toLowerCase()}`;
  const lines: string[] = [];
  lines.push(`Table ${tableName} {`);
  lines.push(indent(`${keyAttrName(e1)} int [ref: > ${e1.name}.${keyAttrName(e1)}]`));
  lines.push(indent(`${keyAttrName(e2)} int [ref: > ${e2.name}.${keyAttrName(e2)}]`));
  for (const attr of rel.attributes) {
    lines.push(indent(attributeToColumn(attr)));
  }
  lines.push(indent(`Note: '${rel.name} (N:M junction)'`));
  lines.push("}");
  return lines.join("\n");
}
